name: 'build test deploy'

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        db: [ 'derby', 'mysql', 'postgresql' ]
        java: [ 11, 17, 21 ]

    steps:
      - name: Checkout...
        uses: actions/checkout@v4

      - name: Set up JDK...
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and test...
        run: mvn clean verify -U -P ${{ matrix.db }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout...
      uses: actions/checkout@v4

    - name: Set up JDK...
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'
    - name: Deploy...
      run: mvn clean source:jar javadoc:javadoc deploy -U -DskipTests --settings .github/workflows/maven_settings.xml
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
